//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrisakContacts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HrisakDBEntities : DbContext
    {
        public HrisakDBEntities()
            : base("name=HrisakDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAddress> tblAddresses { get; set; }
        public virtual DbSet<tblPeople> tblPeoples { get; set; }
        public virtual DbSet<tblPersonToAddress> tblPersonToAddresses { get; set; }
        public virtual DbSet<vwPersonMainList> vwPersonMainLists { get; set; }
    
        public virtual ObjectResult<prGetCityStateFromZip_Result> prGetCityStateFromZip(string zip)
        {
            var zipParameter = zip != null ?
                new ObjectParameter("Zip", zip) :
                new ObjectParameter("Zip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetCityStateFromZip_Result>("prGetCityStateFromZip", zipParameter);
        }
    
        public virtual int prAddPersonAddress(string lastName, string firstName, string birthDate, string cellPhone, string emailAddress, string street, string city, string state, string zipCode)
        {
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var birthDateParameter = birthDate != null ?
                new ObjectParameter("BirthDate", birthDate) :
                new ObjectParameter("BirthDate", typeof(string));
    
            var cellPhoneParameter = cellPhone != null ?
                new ObjectParameter("CellPhone", cellPhone) :
                new ObjectParameter("CellPhone", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("Street", street) :
                new ObjectParameter("Street", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("ZipCode", zipCode) :
                new ObjectParameter("ZipCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prAddPersonAddress", lastNameParameter, firstNameParameter, birthDateParameter, cellPhoneParameter, emailAddressParameter, streetParameter, cityParameter, stateParameter, zipCodeParameter);
        }
    
        public virtual int prDeletePerson(Nullable<int> personToAddressID)
        {
            var personToAddressIDParameter = personToAddressID.HasValue ?
                new ObjectParameter("PersonToAddressID", personToAddressID) :
                new ObjectParameter("PersonToAddressID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDeletePerson", personToAddressIDParameter);
        }
    }
}
