//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrisakContacts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonToAddress
    {
        public int PersonToAddressID { get; set; }
        public int PersonID { get; set; }
        public int AddressID { get; set; }
    }
}
